# ============================================
# Alex.Dots - Starship Prompt Configuration
# ============================================
# Documentation: https://starship.rs/config/
# ============================================

# Timeout for commands (ms)
command_timeout = 3600000

# Newline between prompts
add_newline = true

# Palette
palette = "catppuccin_mocha"

# ============================================
# Prompt Format
# ============================================
format = """\
($directory)\
$os\
$git_branch\
$git_status\
$fill\
$nodejs\
$rust\
$golang\
$php\
$bun\
$java\
$c\
$conda\
$zig\
$cmd_duration\
$time\
\n$character\
"""

# ============================================
# Fill
# ============================================
[fill]
symbol = ' '

# ============================================
# Palette Catpuccin mocha
# ============================================
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# ============================================
# Character (prompt symbol)
# ============================================
[character]
success_symbol = "[ ](fg:green)"
error_symbol = "[ ](fg:red)"
vimcmd_symbol = "[N](bold red)"
vimcmd_replace_one_symbol = "[R](bold peach)"
vimcmd_visual_symbol = "[V](bold mauve)"

# ============================================
# username 
# ============================================
[username]
style_user = 'bold blue'
style_root = 'bold red'
format = '[󱗞 $user](fg:$style) '
disabled = false
show_always = true

# ============================================
# Directory
# ============================================
[directory]
format = "[$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 2
style = "fg:blue"
read_only_style = "fg:blue"
before_repo_root_style = "fg:blue"
truncation_symbol = "…/"
truncate_to_repo = true
read_only = "  "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
#"work" = " "

# ============================================
# cmd Duration
# ============================================
[cmd_duration]
format = " took [ $duration]($style) "
style = "bold fg:yellow"
min_time = 500

# ============================================
# Git Branch
# ============================================
[git_branch]
format = "-> [$symbol$branch]($style) "
style = "bold fg:mauve"
symbol = " "

# ============================================
# Git Status
# ============================================
[git_status]
style = "bold red"
format = '([$all_status$ahead_behind]($style) )'
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "S"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "x${count}"

# ============================================
# Modules
# ============================================
[bun]
version_format = "$raw"
format = '[[ $symbol ($version) ](fg:text)]($style)'
disabled = false

[nodejs]
symbol = " "
format = '[[ $symbol ($version) ](fg:green)]($style)'

[time]
disabled = false
time_format = "%R"
format = '[[   $time ](fg:subtext0)]($style)'

# ============================================
# Disabled Modules (for performance)
# ============================================
[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true

[docker_context]
disabled = true

[package]
disabled = true
