gui:
  nerdFontsVersion: "3"
  scrollPastBottom: false
  border: "rounded"
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  commitLength:
    show: true
  showNumstatInFilesView: true
  # commandLogSize: 8
  statusPanelView: allBranchesLog

  branchColors:
    "feature": "#a6e3a1"
    "hotfix": "#f38ba8"
    "release": "#f9e2af"
    "bugfix": "#fab387"
    "fix": "#fab387"
    "chore": "#89b4fa"

  theme:
    activeBorderColor:
      - "#a6e3a1"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#a6e3a1"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
