# Open lazygit in a popup [<C-a> g](80% width and height)
bind g display-popup -B -s 'bg=#1e1e2e' -d '#{pane_current_path}' -w 80% -h 80% -E lazygit

# Toggle floating terminal [Alt+g]
bind -n M-g if-shell -F '#{==:#{session_name},scratch}' {
  detach-client
} {
  display-popup -d '#{pane_current_path}' -w 80% -h 80% -E "tmux new-session -A -s scratch"
}

# Kill all other sessions [<C-a> K]
bind K confirm-before -p "Kill all other sessions? (y/n)" "kill-session -a"
