# Open lazygit in a popup [<C-a> g](80% width and height)
bind g display-popup -B -s 'bg=#1e1e2e' -d '#{pane_current_path}' -w 80% -h 80% -E lazygit

# Toggle floating terminal [Alt+g]
bind -n M-g if-shell -F '#{==:#{session_name},scratch}' {
  detach-client
} {
  display-popup -d '#{pane_current_path}' -w 80% -h 80% -E "tmux new-session -A -s scratch"
}

# Open Claude Code in a persistent popup per project [<C-a> y]
bind -r y run-shell '\
  SESSION="claude-$(echo #{pane_current_path} | md5sum | cut -c1-8)"; \
  tmux has-session -t "$SESSION" 2>/dev/null || \
  tmux new-session -d -s "$SESSION" -c "#{pane_current_path}" "claude"; \
  tmux display-popup -w80% -h80% -E "tmux attach-session -t $SESSION"'

# Kill all other sessions [<C-a> K]
bind K confirm-before -p "Kill all other sessions? (y/n)" "kill-session -a"
